//each room has a name "A" for instance. World Assembly is where each room goes
const roomTemplates = {
    " ": {
        bitmap: [

        ],
    }, // An empty room for the " " character.
    A: {
        bitmap: [
            "#########################################",
            "#@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@@#",
            "#@@@@@@@@         @@@@@@@         @@@@@@@",
            "#@@@@@@@           @@@@@@           @@@@@",
            "#@@@@@@@           @@@@@@           @@@@@",
            "#@@@@@@@           @@@@@           @@@@@@",
            "#@@@@@@@           @@@@@          #######",
            "#@@@@@@@           @@@@@    ###     #####",
            "##@@@@@@@@        @@@@###            ####",
            "##@@@@@@@@@  ######@@@@@@            ####",
            "###@@@@@@@@  ######@@@@@@            ####",
            "###@@@@@@@@@########@@@@@            ####",
            "####@@   @@@########@@@@@@          #####",
            "####@     @##########@@@@@@@@@     ######",
            "#####     @##############################",
            "#########################################",
            "#########################################",
            "#########################################",
        ],  
        entities: {
            '1': (x, y) => new MPowerPillar(x, y - 1.8, 'ball'),
            '2': (x, y) => new MPowerPillar(x, y - 1.8, 'groundedTeleport'),
            '3': (x, y) => new MPowerPillar(x, y - 1.8, 'groundPound'),
            '4': (x, y) => new MPowerPillar(x, y - 1.8, 'fullTeleport'),
            'H': (x, y) => new MPothead(x, y),
            'Y': (x, y) => new MMimic(x, y - 0.3), // why is this Y? ftlogidk
            'M': (x, y) => new MMinitaur(x, y - 0.3),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'N': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "nl changed this line lol",
                "he probably wont change it back",
                "while typing this",
                "he noticed it was predicting his text",
                "this is really weird lol",
            ], 'pakala'),
            'K': (x, y) => new MNPC(x, y - 0.6, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'kili'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'sign'),
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
            // 'V': (x, y) => new MBreakWall(x, y, 'grassyBreakWall', 'right'),
            // 'U': (x, y) => new MBreakWall(x, y, 'mushroomBreakWall','right'),
        },
    },
    B: {
        bitmap: [
            "################################",
            "#@     @@@@@@   @@@@@@@@@@######",
            "@@@@    @@@       @@@@@@@@@@@@@@",
            "@@@@@                @@@@@@@@@@@",
            "@@@@@                    @@@@@@@",
            "@@@@@                   ########",
            "###@@@@                    #####",
            "###@@@@             ###     ####",
            "#####@@@@                   ####",
            "#####@@@@       ###         @###",
            "#######@@@@               @@@###",       
            "#######@@@@ ###        @@@@@@###",
            "#########@@@@    @@@@@@@@@@@@###",
            "#########@@@@@@@@@@@@@@@@@@@####",
            "################################",
            "################################",
            "################################",
            "################################",
        ],
        entities: {
            'T': (x, y) => new MNPC(x, y - 0.5, [
                "Hey there traveler.",
                "Name's Tomo.",
                "Watch out for the",
                "crystal spikes...",
            ], 'tomo'),
            'L': (x, y) => new MNPC(x, y - 0.5, [
                "I've been here",
                "a long time.",
                "Too long.",
            ], 'lupa'),
            'K': (x, y) => new MNPC(x, y - 0.5, [
                "Don't touch me.",
            ], 'kasi'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "-> Warning: Danger ahead",
            ], 'sign'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            //TODO
            //'P': (x, y) => new MEyecrawler?.(x, y),
            //'M': (x, y) => new MMimic?.(x, y),
        },
    },
    C: {
        bitmap: [
            "######################     #######",
            "#######################     ######",
            "@@@@@   @@@@@@@             W  @@@",
            "@@@@@   @@@@            ##     @@@",
            "@@@@@@@ @@@@                    @@",
            "######@@@@@@@               ######",
            "######@@@@@###########      ######",
            "#######@@@@@@#######   @@@@#######",
            "#########@@@@@###     @@##########",
            "###@@@@@@@@@@@###@@@@@@@@@@@@@@###",
            "##@@@   @@@###########@@@@   @@@##",
            "##@@@   @@@##@@@@@@@@####### @@@##",
            "##@@@   @@###@@@@@@@@@@@@@   @@@##",
            "###@@@@@@@###@@@@@@@@@@@@@@@@@####",
            "#############@@@@@@@@#############",
            "###############@@@################",
            "###############@@@@###############",
        ],
        entities: {
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
        },
    },
    D: {
        bitmap: [
            "###############    #######",
            "##         ##        #####",
            "#          ##        #####",
            "#          ##        #####",
            "#         @##@      @#####",
            "#         @##@@    @@#####",
            "#    C    @@#@@@@@@@@#####",
            "#   #### @@@@@@@@@@@@#####",
            "#   ####@@@@@@@@@@@@@#####",
            "#   #####@@@@@@@@@@@@#####",
            "#   #####@@@@@@@@@@@@#####",
            "#  @##########@@@@@@######",
            "#  @######################",
            "# @@@@@@@@@@@@##@@#@@@@@#@",
            "#@@@@@@@@@@@@@@@@@@@@@@@@@",
            "##@@@###@@@#@@@@@@@@@##@@@",
            "##########################",
            "##########################",
            "##########################",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
        },
    },
    E: {
        bitmap: [
            "##########################",
            "##@@@@@@@@       @@@@@@###",
            "#@@@@@              @@@@##",
            "#@@@@                 @@##",
            "#@@@@                  @##",
            "#@@@@                  @##",
            "#@@@@                 @###",
            "#@@@@@@             ######",
            "#@@@@@@@             @@@@@",
            "#@@@@@@#######       @@@@@",
            "#@@@@@@@####         @@@@@",
            "####@@@@###@    ####@@@@@@",
            "##@@@@@@###@@      @@@@@@@",
            "@@@@@@@####@@     @@@@@###",
            "@@@@@@@####@@@ M @@@@@####",
            "@@@@@@######@@   @@@@#####",
            "##########################",
            "##########################",
            "##########################",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    F: {
        bitmap: [
            "############################################",
            "#@@@@@             @@@@@@@@####@@@@@@@@@####",
            "#@@@@@          @@@@@@@@@@@####@@@@@@@@@####",
            "#@@@             @@@@@@@##########@@@@@@####",
            "#@@            @@@@@@@@    #### @@@@@@@@####",
            "#@@@M      ##########@     ####   @@@#######",
            "##@@@ #       #####@@@     ####             ",
            "#########     ####@@@      #####            ",
            "######        ####@@@   M  ####             ",
            "@@@@##     #######@@@@     ####             ",
            "@@@@##        ####@@@@@@@@ ####         ####",
            "@@@@#####     ####@@@@@@@@@#######     #####",
            "@@@@          ####@@@@@@@@@@@         ######",
            "##@@@@    ########@@@@@@@@@@@@@@     #######",
            "##################@@@@@@@@@#################",
            "############################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    G: {
        bitmap: [
            "#################",
            "##@@@@@@@@@@@@@##",
            "#@@@@@     @@@@@#",
            "#@@@@       @@@@#",
            "####         ####",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "                 ",
            "####         ####",
            "#@      1      @#",
            "#@@@  #####  @@@#",
            "#@@@@@#####@@@@@#",
            "#@@@@#######@@@@#",
            "#@@@@#######@@@@#",
            "#################",
        ],
        entities: {
            '1': (x, y) => new MPowerPillar(x - 0.5, y - 1.8, "ball"),
        },
    },
    H: {
        bitmap: [
            "##########@@@@###",
            "##########@@@@@##",
            "###########@@@@@#",
            "###########@@@@@#",
            "##       @##@@@@#",
            "         @##@@@@#",
            "        @@@##@@@#",
            "      @@@@@##@@@#",
            "     @@@@@@@@@@##",
            "     @@@@@@@@@@##",
            "## @@@###########",
            "##@@#############",
            
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    I: {
        bitmap: [
            "################",
            "################",
            "################",
            "################",
            "#####         ##",
            "##            ##",
            "#            @##",
            "#            @##",
            "#         @  @##",
            "#         @  @##",
            "#         @@ @##",
            "          @@@@##",
            "         @@@@@##",
            "        @@@@@@##",
            "    C @@@@@@@@##",
            "##########@@@@##",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3), 
            'Y': (x, y) => new MMimic(x, y - 0.3),
            'F': (x, y) => new MFlyer(x, y),
            'Q': (x, y) => new MSwarmer(x, y, 5),
        },
    },
    J: {
        bitmap: [
            "########################",
            "########################",
            "########################",
            "########################",
            "##        @@@@@@@@@@@###",
            "#              @@@@M@@##",
            "#                @@@@@##",
            "#                 ######",
            "                     ###",
            "        @@@@          ##",
            "     @@@@@####        ##",
            "   @@@@ @@##@@          ",
            "# @@@@@@@###@@@@###     ",
            "##@@@M@@@###@@@@@       ",
            "##@@@@@@######@@@       ",
            "########################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        },
    },
    K: {
        bitmap: [
            "####################################################",
            "######          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##",
            "@@@                    @@@@@@@@@@@       @@@@@@@@@@#",
            "@@@                    @@@@@@@@@            @@@@@@@#",
            "@@@@                    @@@@@@@@              @@@@@#",
            "########    ##            @@@@@               @@@@@#",
            "######      ######                             @@@@#",
            "###### @@@@   ####                                 #",
            "######@@@@@@@ #####                                 ",
            "######@@@@@ @@#####                                 ",
            "######@@@@@@@@######    ####                        ",
            "######@ @@@@@#######                                ",
            "######@@@@@@@@@                ####             ####",
            "######@@@@@@@@@@@      @@@@@@@#####             ####",
            "######@@M@@@@@@@@@@@@@@@@M@@@@######    M      #####",
            "######@@@@@###########@@@@@@@#######           #####",
            "####################################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'R': (x, y) => new MBlob(x, y, "r2"),
        },
    },
    L: {
        bitmap: [
            "######################################",
            "#@         @@@@@@@@@@@@@@@@         @#",
            "@@            @@@@@@@@@@            @@",
            "@@@             @@@@@@             @@@",
            "@@@              @@@@            ##@@@",
            "#####  M                      M  #####",
            "##@@##    ##              ##    ##@@##",
            "#@@@########              ########@@@#",
            "#@@@@######    ## N  ##    ######@@@@#",
            "#@@@@@@@@     ##########     @@@@@@@@#",
            "#@@@@@@@@@@@@@##########@@@@@@@@@@@@@#",
            "#@@@@@@@@@@@@############@@@@@@@@@ @@#",
            "#@@@@@@@@@@@@############@@@@@@@@@@@@#",
            "#@@@@@@M@@@@##############@@@@M@@@@@@#",
            "##@@@@@@@@@################@@@@@@@@@##",
            "######################################",
            "######################################",
            "######################################",
            "######################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
            'N': (x, y) => new MNPC(x + 0.2, y - 0.5, [
                "Normally,",
                "This room would be a gauntlet.",
                "The doors at either side would close.",
                "And you'd have to beat up the badguys.",
                "But nobody implemented that yet...",
                "...so you get me, instead.",
                "*Hef, hef, horf!*",
            ], "pakala"),
        }
    },
    M: {
        bitmap: [
            "################",
            "#####@@@@@@@@###",
            "####@@    @@####",
            "###        @@@##",
            "#    @@        #",
            "#@            ##",
            "#@       @      ",
            "#@@@            ",
            "###@@@      ####",
            "################",
            "################",
        ],
        entities: {

        }
    },
    N: {
        bitmap: [
            "##@@##################################",
            "#@@@@@                 ###############",
            "#@@@@@@@@              ###############",
            "###############         ##############",
            "################           @@@@@@@####",
            "################               @@@@###",
            "       @@@@@#######               @@@#",
            "           @@@##            @@@@   @@#",
            "###          @@#     ###  @@@@ @@@  @#",
            "#              #          @@@@@@@@@ @#",
            "#@   ##   @@   #         @###@ @@@@@@#",
            "#@             #         @@@@ @@@@@  #",
            "#@    @ ##  @@ #          @@@@@###@@@#",
            "#@@            #        @@@@@@@@@@ @@#",
            "#@@@@        ###         @@@@@@@@@@ ##",
            "#@ @@       ####   M    @@@ @@@@@@@@##",
            "#@@@@    #######         @@@  @@@@####",
            "##@ @@@@              @@@@@@@@@#######",
            "######@@@@@     @@@@@@@@@@@@##########",
            "######################################",
        ],
        entities: {
            'M': (x, y) => new MMinitaur(x, y),
        }
    },
    O: {
        bitmap: [
            "BBBBBBBBBBBBBB####################",
            "BBBBBBBBBBBBB#####################",
            "BBBBBBB###########################",
            "bbbbbbb            ###############",
            "bbbbbb             ###############",
            "bbbbbb  b            #############",
            "bbbbbbbbb            #############",
            "bbbbbbbb               ###########",
            "bbbbbbbb   bbbb        ###########",
            "BBbbbbbbbbbb             #########",
            "BBbbbbbbbbb              #########",
            "BBBBbbbbbb                 #######",
            "##BBbbbbbb  b              #######",
            "###BBBbbbbbbb              #######",
            "####BBbbbbbb               #######",
            "######BBBbbbb              #######",
            "########BBBbbb C           #######",
            "######################     #######",
        ],
        entities: {
            'C': (x, y) => new MCheckpoint(x, y - 3),
        },
    },
    P: {
        bitmap: [
            "BBbbbbbbBBBBBBBBBBBBBB",
            "B   bbbbbbbbbbbBBBBBBB",
            "B   BBBbbbbbbbbbBBBBBB",
            "B         bbbbbbbbbbbb",
            "BB       bb   bbbbbbbb",
            "BB             bbbbbbb",
            "BBBB           bbbbbbb",
            "BBbb  BBBB    bbbbbbbb",
            "Bbb   BBB   BBBB bbbbb",
            "BBbb        BBB    BBB",
            "BBbbbbb            BBB",
            "BBbbbbbbb b       BBBB",
            "BBbbbbbbbbb       BBB#",
            "BBbbbbbbbb     E BBB##",
            "BBbbbbbbbbbbb    BB###",
            "#BBbbbbbbbbb  ########",
            "#####bbbb#############",
            "######################",
            "######################",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
    },
    Q: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBbBBBBBBBBBBB",
            "BBBBBBBBBBB BBBBBBBBBBbbbbBBBBBBBBB",
            "BBBBBBBBB    BBBBBBBBbbbbbbbBBBBBBB",
            "BBBbbbb             bb  bbbbbbbbbbb",
            "BBbbb bbb               bbbbbbbbbbb",
            "BBbbb                  bBBBBBBBBBBB",
            "BBbbb                  BBBBBBBBBBBB",
            "BBbb                  BBBbBBBbbBBBB",
            "Bbbbbb               EBBbbBbBbbbBBB",
            "Bbbbb       BB    BBbbbbbbbbBbbbbbb",
            "bbbbbbb    BBBBBBBBBBbbbbbbbbbbbbbb",
            "bbbbbbbbbb BBBBBBBBBBBbbbbbbbbbbBBB",
            "bbbbbbbbbbBBBBBBBBBBBBBbbbbbbbbBBBB",
            "BbbbbbbbbbBBBBBBBBBBBBBbbbbbbbbBBBB",
            "BBbbbbbbBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
    },
    R: {
        bitmap: [
            "BBBBBBBBBBBBBBBBB",
            "bbbbbBBBBBBBBBBBB",
            "bbbbbbBBBBBBBBBBB",
            "bbbbbbbbbbbbbBBBB",
            "bbbbbbbbbbbbbbBBB",
            "bbbbbbbbbbbbbbBBB",
            "bbbbbbbbbbbbbbBBB",
            "BBBbbbbbbbbbbbBBB",
            "BBbbbbbbbbbbbBBBB",
            "BBbbbBBBBBBBBBBBB",
            "BBbbbb     bbbBBB",
            "BBBbbbb     bbBBB",
            "BBBbb b     bbbBB",
            "BBBBB        bbbb",
            "BBBBBBB    bbbbbb",
            "BBBbbb  bbbbbbbbb",
            "BBBbbbbbBBBBbbbBB",
            "BBBBBBBBBBBBBBBBB",

        ],
        entities: {

        },
    },
    S: {
        bitmap: [
            "BBBBBBBBBBBBBBBBBBBBBBB      ",
            "BBBBBBBBBB     BBBBBB        ",
            "BBBBBBBBBBB     BB           ",
            "BBBBbbbbbb       BB          ",
            "BBBBBbb                      ",
            "BBbbbbbbb                    ",
            "bbbbbb  bbb                  ",
            "bbbbbb                       ",
            "Bbbbbbbbbb       BBBBBB      ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBbbbBBBBBBBBBBBBBBBBBBB",
            "bbbBBbbbbbbBBBBBBBBBBBBBBBBBB",
            "bbbbbbbbbbbBBBBBBBBBBBBBBBBBB",
            "BBbbbbbbbbbBBBBBBBBBBBBBBBBBB",
            "BBBBBbbbbbBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            
        },
    },
    T: {
        bitmap: [
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "                                            ",
            "BBBBBB                                      ",
            "BBBBBBBBBBB                                 ",
            "BBBBBBBBBBBBBBB          BBBBBBBBB          ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB      ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {

        },
    },
    U: {
        bitmap: [
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                                    ",
            "                        BBBBB       ",
            "                      BBBBBbbbb     ",
            "            S       BBBBBBBbbbbBB   ",
            "         BBBBBBBBBBBBBBBBBBBbbbBBB  ",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",

        ],
        entities: {
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Awen Outpost\n->",
                "West Castle Tower\n<-",
            ], 'sign'),
        },
    },
    V: {
        bitmap: [
            "                                      ",
            "                                      ",
            "                                      ",
            "                                      ",
            "                                      ",
            "                                      ",
            "                      BBBBBBBBBBBBBBBB",
            "                 BBBbbBBBbbbbBBBBBBBBB",
            "            BBBbbbbbbbbbbbbbbbbbbBBBBB",
            "     BBBBB  bbbbbbbbbbbbbbbbbbbbbbBBBB",
            "    BBBBBB bbbbbbbbbbbbbbbbbbbbbbbbBBB",
            "   BBBBBBBBbbbbbbbbbbbbbbbbbbbbbbbbBBB",
            " BBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbbbbBBB",
            "BBBBBBBBBBBBBBBBbbbbbbbbbbbbbbbbbbBBBB",
            "BBBBBBBBBBBBBBBBBBBbbbbbbbbbpbbBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'p': (x, y) => new MNPC(x - 0.5, y - 0.5, [
                "Normally, there'd be a buncha NPCs down here...",
                "To give you advice and sell stuff.",
                "But nobody implemented that yet...",
                "...so you get...",
                "...Me.",
                "Instead.",
                "I know you're reading this, Arrow.",
                "*Hef, hef, horf!*",
            ], 'pakala'),
        }, // Lotsa NPCs for this one. :)
    },
    W: {
        bitmap: [
            "                              ############@@@@@@############",
            "                              ###########@@@@@@@@###########",
            "                            ############@@@@##@@@@##########",
            "                            ###########@@@@####@@@@#########",
            "                          ############@@@@######@@@@########",
            "  S      BB      E        ###########@@@@########@@@@#######",
            "BBBBBBBBBBB             ############@@@@##########@@@@######",
            "BBBBBBBBBBBBBBBBBBBBBBBB###########@@@@############@@@@#####",
            "BBBBBBBBBBBBBBBBBBBBBB############@@@@##@@@@@@@@@@##@@@@####",
            "BBBBBBBBBBBBBBBBBBBBBB###########@@@@##@@@@@@@@@@@@##@@@@###",
            "BBBBBBBBBBBBBBBBBBBB############@@@@##@@@@@@@@@@@@@@##@@@@##",
            "BBBBBBBBBBBBBBBBBBBB############@@@##@@@@###@@###@@@@##@@@##",
            "BBBBBBBBBBBBBBBBBBBB############@@@@@@@@@@##@@##@@@@@@@@@@##",
            "BBBBBBBBBBBBBBBBBB###############@@@@@@@@@##@@##@@@@@@@@@###",
            "BBBBBBBBBBBBBBBBBB################@@@@@@@@##@@##@@@@@@@@####",
            "BBBBBBBBBBBBBBBB############################@@##############",
            "BBBBBBBBBBBBBBBB############################@@##############",
            "BBBBBBBBBBBBBB##############################@@##############",
        ],
        entities: {
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "Awen Outpost\n<-",
                "Central Castle Tower\n->",
            ], 'sign'),
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
        },
    },
    X: {
        bitmap: [
            "                                                            ",
            "                                    ##  ##  ##  ##  ##      ",
            "                                    ##  ## C##  ##  ##      ",
            "                                    ##################      ",
            "                                    ##################      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    ##@@@@@@@@@@@@@@##      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                    @@@@@@@@@@@@@@@@@@      ",
            "                                  ####@@@########@@@####    ",
            "                                  #####@@@######@@@#####BBBB",
            "                                ########@@@@@@@@@@########BB",
            "                                #########@@@@@@@@#########BB",
            "                              ############@@@@@@############",
        ],
        entities: {
            "C": (x, y) => new MCheckpoint(x + 1, y + 8),
        },
    },
    Y: {
        bitmap: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "               eE           ",
            "       bbBBBBBBbbb          ",
            "    BBbbbbbbbbbbbbBBB   S   ",
            "   BBbbbbbbbbbbbbbbBBBBBBBBB",
            "BBBBBbbbbbbbbbbbbbbBBBBBBBBB",
            "BBBBBBBbbbbbbbbbbbBBBBBBBBBB",
            "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        ],
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "WARNING",
                "Chasm ahead.",
                "To avoid falling, excercise caution.",
                "Central Castle Tower <-",
            ], "sign"),
        },
    },
    Z: {
        bitmap: [
            "BB   BBBBBBBBBBBBB",
            "BB     BBBBbbbbbbb",
            "BBBB   BBBbbbbbbbb",
            "BB     BBB bbbbbbb",
            "BB   BBBBB  bbbbbb",
            "BB     BBB    bbbb",
            "BBBB   BBB     bbb",
            "BBbbbb BBBB###BBBB",
            "BBbbbBBBBB  S BBBB",
            "BBbbbbb          B",
            "BBBbbbbbbb       B",
            "BBBBBBBBBBBBB    B",
            "BBBBBBBBBBB      B",
            "BBBBBBBBBBB    BBB",
            "BBBBBBBBBBB      B",
            "BBBBBBBBBBBBB    B",
        ],
        entities: {
            "S": (x, y) => new MNPC(x - 0.3, y - 2.5, [
                "There should be...",
                "A ground pound floor here."
            ], "sign"),
        },
    },
};

const worldAssembly = [
    "      XY",
    "ZRQSTUVW",
    "  PO", 
    " ABCLKJI",
    "   DEFGH",
    "      MN",
];

