//each room has a name "A" for instance. World Assembly is where each room goes
const roomTemplates = {

    A: {
        bitmap: [
            "####################",
            "#                  #",
            "#  ###             #",
            "#                  #",
            "#          K       #",
            "#        ######    #",
            "#                  #",
            "#   ###            #",
            "#   #              #", 
            "#         ######   #",
            "#        ##        #",
            "#  W               #",
            "#              ##  #",
            "#       @@@@       #",
            "#  ###              ",
            "#                  W",
            "#   BBBB            ",
            "# e E BB  C     N   ",
            "####################",
        ],  
        entities: {
            'E': (x, y) => new MBlob(x, y, 'g2'),
            'e': (x, y) => new MBlob(x, y, 'g1'),
            'C': (x, y) => new MCheckpoint(x, y - 3),
            'N': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'pakala'),
            'K': (x, y) => new MNPC(x, y - 0.6, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'kili'),
            'S': (x, y) => new MNPC(x, y - 0.5, [
                "hiiiii",   
                "My name is classified",
                ".",
                "..",
                "...",
                "You don't know me son",
            ], 'sign'),
            'W': (x, y) => new MBreakWall(x, y, 'brickBreakWall', 'right'),
            // 'V': (x, y) => new MBreakWall(x, y, 'grassyBreakWall', 'right'),
            // 'U': (x, y) => new MBreakWall(x, y, 'mushroomBreakWall','right'),
        },
    },

    // B: [
    //     "####################",
    //     "                   #",
    //     "#   i              #",
    //     "#   ##             #",
    //     "#          h       #",
    //     "#         ###      #",
    //     "#    g             #",
    //     "#    ##            #",
    //     "#              f   #",
    //     "#              ##  #",
    //     "#    d             #",
    //     "#   ####           #",
    //     "#                  #",
    //     "#         c        #",
    //     "         ##        #",
    //     "                   #",
    //     "                   #",
    //     " a   j         b   #",
    //     "########     #######",
    // ],
    B: [
        "####################",
        "                   #",
        "#                  #",
        "#   ##             #",
        "#                  #",
        "#         ###      #",
        "#                  #",
        "#    ##            #",
        "#                  #",
        "#              ##  #",
        "#                  #",
        "#   ####           #",
        "#                  #",
        "#                  #",
        "         ##        #",
        "                   #",
        "                   #",
        "     a             #",
        "########     #######",
    ],
    C: [
        "####################",
        "#                  #",
        "#   ##             #",
        "#                  #",
        "#          ###      ",
        "#                  #",
        "#     ###          #",
        "#                  #",
        "#                   ",
        "#              ##  #",
        "#                  #",
        "#  ##              #",
        "#                  #",
        "#                   ",
        "#                   ",
        "#                   ",
        "####################",
    ],

    D: [
        "########     #######",
        "#                  #",
        "#                  #",
        "#        ##        #",
        "#                  #",
        "#  ##              #",
        "#                  #",
        "#           ###    #",
        "#                  #",
        "#    ##            #",
        "#                  #",
        "#              ##  #",
        "#                  #",
        "                   #",
        "                   #",
        "                   #",
        "####################",
    ],

};

const worldAssembly = [ 
    "AB",
    "CD",
];

